<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'franciscoblancojn\\wordpress_utils\\' => array($vendorDir . '/franciscoblancojn/wordpress_utils/src'),
);
