<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitWPFM
{
    public static $prefixLengthsPsr4 = array (
        'f' => 
        array (
            'franciscoblancojn\\wordpress_utils\\' => 34,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'franciscoblancojn\\wordpress_utils\\' => 
        array (
            0 => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'franciscoblancojn\\wordpress_utils\\FWUCollapse' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUCollapse.php',
        'franciscoblancojn\\wordpress_utils\\FWUComponent' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUComponent.php',
        'franciscoblancojn\\wordpress_utils\\FWUExportImport' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUExportImport.php',
        'franciscoblancojn\\wordpress_utils\\FWUModal' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUModal.php',
        'franciscoblancojn\\wordpress_utils\\FWUPage' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUPage.php',
        'franciscoblancojn\\wordpress_utils\\FWURespond' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWURespond.php',
        'franciscoblancojn\\wordpress_utils\\FWUSystemLog' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUSystemLog.php',
        'franciscoblancojn\\wordpress_utils\\FWUTooltip' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUTooltip.php',
        'franciscoblancojn\\wordpress_utils\\FWUUpdate' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUUpdate.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitWPFM::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitWPFM::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitWPFM::$classMap;

        }, null, ClassLoader::class);
    }
}
