<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'franciscoblancojn\\wordpress_utils\\FWUCollapse' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUCollapse.php',
    'franciscoblancojn\\wordpress_utils\\FWUComponent' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUComponent.php',
    'franciscoblancojn\\wordpress_utils\\FWUExportImport' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUExportImport.php',
    'franciscoblancojn\\wordpress_utils\\FWUModal' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUModal.php',
    'franciscoblancojn\\wordpress_utils\\FWUPage' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUPage.php',
    'franciscoblancojn\\wordpress_utils\\FWURespond' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWURespond.php',
    'franciscoblancojn\\wordpress_utils\\FWUSystemLog' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUSystemLog.php',
    'franciscoblancojn\\wordpress_utils\\FWUTooltip' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUTooltip.php',
    'franciscoblancojn\\wordpress_utils\\FWUUpdate' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUUpdate.php',
);
